### ISSUE TITLE
Crash upon importing spi1d lut for modification

### ISSUE THREAD

**Issue by Phoust** [EatTheFuture/image_tools#10]
Loading an spi1d LUT into the LUT Maker 'modify' tab results in a crash on Windows. Initially discovered when importing Blackmagic Gen5 to lin, but the error is reproducible with any spi1d LUT including ACES transforms. Regardless, I have attached the original LUT as an example

Windows 10 Home 21H1,
Threadripper 3960x, 
RTX 3090, 
128GB 2400MHz
[Film Gen 5 - Transfer Function.zip](https://github.com/EatTheFuture/image_tools/files/8782670/Film.Gen.5.-.Transfer.Function.zip)

**Comment by cessen** [comment]
Fixed!  Here's a new dev build with the fix:
https://github.com/EatTheFuture/image_tools/releases/tag/dev_build-2022_05_26-5e9a344
