### ISSUE TITLE
HDRI Merge freezes/crashes upon dragging in images

### ISSUE THREAD

**Issue by Phoust** [EatTheFuture/image_tools#11]
Pretty much what the title says: Importing via the drop down menu works as expected, but attempting to drag one or more images from the file explorer into HDRI merge triggers a freeze from which it does not recover. Tried with various image formats and amounts. Tested in windows 10.

**Comment by cessen** [comment]
Thank you for the crash report!

A question and a request to help track this down:

1. What version of ETF Image Tools are you using?  0.3.1?
2. If you have the time, could you download the latest [dev build](https://github.com/EatTheFuture/image_tools/releases/tag/dev_build-2022_06_22-e6d1fd8), launch it from a console, make it crash as described, and then post the console output here?

Thanks!

**Comment by cessen** [comment]
I was able to repro on Linux as well, so it doesn't appear to be Windows-specific.

It looks like it started happening when I upgraded to a newer version of the GUI library that ETF Image Tools uses.  But LUT Maker doesn't have the same issue, so I can probably(?) fix it on this end.

**Comment by cessen** [comment]
Okay, I believe I've fixed it in 237da3840b80c67200bc307bd9902c39696b20a6.

Here's the dev build to test the fix:
https://github.com/EatTheFuture/image_tools/releases/tag/dev_build-2022_07_28-237da38

**Comment by Phoust** [comment]
> Okay, I believe I've fixed it in [237da38](https://github.com/EatTheFuture/image_tools/commit/237da3840b80c67200bc307bd9902c39696b20a6).
> 
> Here's the dev build to test the fix: https://github.com/EatTheFuture/image_tools/releases/tag/dev_build-2022_07_28-237da38

Works perfectly now! You're the best!

**Comment by cessen** [comment]
Awesome!  Thanks so much for your help!
