### ISSUE TITLE
Write permission problem on LInux when using AppImage

### ISSUE THREAD

**Issue by Seb-Perso** [EatTheFuture/image_tools#4]
Hi !

When trying to create an OCIO config with OCIO Maker, I get a
"job Export Config panicked"

In the console I have this :
"thread '<unnamed>' panicked at 'Failed to write OCIO config: Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }', src/bin/ocio_maker.rs:771:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

=> which is weird, because normally the program has the right to write on the folder I specified, actually it's managing to write the folders ""filmic", "luts" and "ocio_maker" but they're empty. It's not a space problem either (I have more than 100Gb space left).

The "Lut Maker" worked without issue.

OS : Linux mint, using AppImages exe files.

**Comment by cessen** [comment]
Thanks for the report!  I'll try to look into this soon.

**Comment by cessen** [comment]
I've managed to reproduce this on a VM running Linux Mint.  Now to figure out what's going on and fix it.

**Comment by cessen** [comment]
I believe I've figured out a fix.  Here's a dev build with the fix in it:
https://github.com/EatTheFuture/image_tools/releases/tag/dev_build-2022_01_12-cc6ce16

@Seb-Perso 
If you could test it out to confirm, that would great!  Thanks!

**Comment by Seb-Perso** [comment]
Hi Nathan,

Confirmed, it works now, thanks a ton !

**Comment by cessen** [comment]
Awesome, thanks!  I'll be cutting a new release soon with the bug fix (and some new features, too!).

**Comment by cessen** [comment]
This is now released in v0.3.0:
https://github.com/EatTheFuture/image_tools/releases/tag/v0.3.0

**Comment by Seb-Perso** [comment]
That's awesome Nathan, thanks !

Le sam. 15 janv. 2022 à 01:12, Nathan Vegdahl ***@***.***> a
écrit :
