### ISSUE TITLE
LUT maker export crash on OSX

### ISSUE THREAD

**Issue by elizarification** [EatTheFuture/image_tools#5]
Clicking the export buttons causes LUT maker to exit on Big Sur on M1. Tried giving it disk access -- didn't help. 
The exit message:

thread 'main' panicked at 'Attempted to construct an Id from a null pointer', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_id-0.1.1/src/id.rs:62:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by cessen** [comment]
Thanks for the report!  I'll look into this the next chance I get (I don't personally have an Apple system, so it might be a little bit... sorry!).

**Comment by elizarification** [comment]
Thanks! If I can help in any way, don't hesitate to ask.

**Comment by g3ntile** [comment]
Hi! I use a mac (hackintosh in fact) and I have exactly the same issue!
(exactly to the letter, the same error)
I can add that I have no /Users/runner/ folder, so it may be something hardcoded somewhere causing the crash.
I tried HDRI Merger and it worked flawlessly, and saved the .hdr with no issues, so I bet that it's something really easy to fix, like a typo or something.
This is an awesome tools, really looking forward to test it.
I don't code, so I can't help with that, but I can assure I'll test the builds :-)
And thank you for taking the time to make this available on macs too!

**Comment by cessen** [comment]
> I tried HDRI Merger and it worked flawlessly, and saved the .hdr with no issues, so I bet that it's something really easy to fix, like a typo or something.

Ah!  This is *super* helpful, actually.  I think I might know what it is then (not 100% sure, of course).  I'll try my hand at fixing it, and make a dev build for you guys to test.

Thanks!

> And thank you for taking the time to make this available on macs too!

Of course!  I want these to be usable by as many people as possible.  It's of course hard for me to test on Mac, since I don't own one.  But my *intention*, at least, is to make everything work just as well on Mac as on Linux and Windows.

**Comment by cessen** [comment]
I've made a development build with the potential fix included:
https://github.com/EatTheFuture/image_tools/releases/tag/dev-build

If either of you get the chance to test it out and let me know if the bug is *actually* fixed or not, I'd really appreciate it!

Thanks!

**Comment by g3ntile** [comment]
Yes!
It worked! it saved the file :-) now I can test the rest of the workflow
Thank you very much!!

**Comment by cessen** [comment]
Awesome!  I'll close this as fixed, then.  If you run into anything else, please don't hesitate to file another issue!

**Comment by cessen** [comment]
This is now released in v0.3.0:
https://github.com/EatTheFuture/image_tools/releases/tag/v0.3.0
